### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by GoodLucky777** [PetteriM1/BlockAPI#1]
I have a few questions about this plugin.

1. How many blocks can be created? Is this plugin or anvil world format have limit?
2. How can I use the custom block textures using resource pack?
3. Are you going to make Wiki for this plugin?
4. How can I add block without extend original block?
5. Can I register block with custom block id?
6. Is this plugin will support Nukkit 2.0?

**Comment by PetteriM1** [comment]
1. The point of this plugin is to provide plugin developers an easy way to override existing blocks to change their behaviour. And yes, the limits of anvil format applies here too.
2. Idk. 
3. No but there is quite much info and a link to an example plugin here: [https://nukkitx.com/resources/blockapi.405/](https://nukkitx.com/resources/blockapi.405/)
4. Just make it not to extend the original block. 😄 However this is not recommended and can cause problems with some blocks.
5. You can register but it probably won't work in game. I haven't tested.
6. There is no Nukkit 2.0 support.
