### ISSUE TITLE
New Block with New ID and Texture

### ISSUE THREAD

**Issue by ViceEye** [PetteriM1/BlockAPI#2]
Hi,

It is possible to load new blocks in new texture with new blockId from texture pack?

If it's, would you consider create a custom Item API as well, these will be very helpful.

Thanks.

**Comment by PetteriM1** [comment]
In theory it's possible but you would have very few free IDs for the new blocks while Nukkit's world format only supports IDs 0-255

**Comment by PetteriM1** [comment]
So replacing existing blocks you don't need is currently the best and the easiest way to go

**Comment by ViceEye** [comment]
Roger that, thank you very much
